# Regression tests for feedback received from a real FreeBSD/INN installation.

use strict;
use warnings;

use File::Path qw(make_path);
use File::Temp qw(tempdir);
use Test::More;
use lib 'lib';
use lib 'tests/lib';

use Postfilter::Checks::Style;
use Postfilter::Checks::Reputation;
use Postfilter::Config;
use Postfilter::HeaderTransform;
use TestPostfilter qw(base_config build_context current_rfc_date test_logger);

# 1. Test dates must be independent of the account locale.  RFC 5536 dates use
# English weekday/month tokens, so the fixture must not inherit LC_TIME.
my $date = current_rfc_date();
like(
    $date,
    qr/^(?:Sun|Mon|Tue|Wed|Thu|Fri|Sat), \d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} \+0000$/,
    'realistic article date is locale-independent RFC-style English',
);
SKIP: {
    skip 'Date::Parse unavailable', 1 unless eval { require Date::Parse; 1 };
    ok(defined Date::Parse::str2time($date), 'locale-independent fixture is parsed by Date::Parse');
}

# 2. A technical rejection in audit mode is accepted by nnrpd.  Header
# finalisation must therefore continue and add configured operational headers.
my $config = base_config();
$config->{policy}{mode} = 'audit';
$config->{headers}{include_new_headers} = 1;
$config->{new_headers}{'X-Postfilter'} = 'Postfilter-NG test';
$config->{distributions} = ['world'];
my $context = build_context(
    config => $config,
    headers => {
        From         => 'Example User <example@example.invalid>',
        Newsgroups   => 'local.test',
        Subject      => 'Audit distribution test',
        Date         => current_rfc_date(),
        'Message-ID' => '<audit-distribution@test.invalid>',
        Distribution => 'trigofacile',
    },
);
my $header_result = Postfilter::HeaderTransform->apply($context);
ok($header_result->is_reject, 'invalid Distribution remains a technical rejection in audit mode');
is($context->{headers}{'X-Postfilter'}, 'Postfilter-NG test', 'audit-accepted article still receives configured new headers');

# 3. Shipped configuration uses one canonical setting for each duplicated path
# and no longer advertises obsolete X-Complaints-To or the retired SORBS DNSBL.
my $main = _slurp('conf/postfilter.toml');
my $reputation = _slurp('conf/conf.d/40-reputation.toml');
my $structural = _slurp('conf/conf.d/10-structural-rules.toml');
unlike($main, qr/^html_output\s*=/m, 'paths.html_output duplicate is not shipped');
unlike($main, qr/^database_privacy\s*=/m, 'keys.database_privacy duplicate is not shipped');
unlike($main, qr/^X-Complaints-To\s*=/m, 'obsolete X-Complaints-To is not generated by default');
unlike($reputation, qr/dnsbl\.sorbs\.net|sorbs-socks-zombies/i, 'retired SORBS provider is not configured');
like($reputation, qr/id\s*=\s*"dronebl".*?zone\s*=\s*"dnsbl\.dronebl\.org"/s, 'DroneBL replaces SORBS in shipped defaults');
like($reputation, qr/ip_versions\s*=\s*\["ipv4"\]/, 'DroneBL is explicitly scoped to IPv4');
unlike($reputation, qr/^\s*"127\.0\.0\.(?:12|17|18|19|255)"\s*,?\s*$/m, 'ambiguous DroneBL classes are not positive defaults');
like($reputation, qr/YOUR_DQS_KEY\.xbl\.dq\.spamhaus\.net/, 'optional Spamhaus XBL DQS example is documented');
like($reputation, qr/YOUR_DQS_KEY\.authbl\.dq\.spamhaus\.net/, 'optional Spamhaus AuthBL DQS example is documented');
unlike($structural, qr/exception_pattern\s*=\s*"\^X-Complaints-To\$"/, 'client-supplied X-Complaints-To is no longer specially allowed');

# 4. IPv4-only DNSBL providers must not be queried for an IPv6 posting client.
my $rbl_config = base_config();
$rbl_config->{modules}{rbl} = 1;
$rbl_config->{dnsbl} = [{
    id             => 'ipv4-only-test',
    enabled        => 1,
    zone           => 'dnsbl.invalid',
    ip_versions    => ['ipv4'],
    positive_codes => ['127.0.0.2'],
    action         => 'reject',
}];
my $rbl_logger = test_logger();
my $rbl_context = build_context(
    config => $rbl_config,
    logger => $rbl_logger,
    attributes => {
        hostname  => 'ipv6.example.invalid',
        ipaddress => '2001:db8::25',
        interface => 'reader.example.invalid',
    },
);
{
    no warnings 'redefine';
    local *Postfilter::Checks::Reputation::_query_ip_list = sub {
        die 'IPv4-only provider was queried for IPv6';
    };
    my $rbl_result = Postfilter::Checks::Reputation->run_rbl($rbl_context);
    ok($rbl_result->is_pass, 'IPv4-only DNSBL is skipped for an IPv6 client');
}
is(
    scalar(grep { $_->{message} eq 'dns_reputation_query' } @{ $rbl_logger->{events} }),
    0,
    'skipped IPv4-only DNSBL emits no DNS query event for IPv6',
);

my $ipv4_context = build_context(
    config => $rbl_config,
    attributes => {
        hostname  => 'ipv4.example.invalid',
        ipaddress => '192.0.2.25',
        interface => 'reader.example.invalid',
    },
);
my $ipv4_queries = 0;
{
    no warnings 'redefine';
    local *Postfilter::Checks::Reputation::_query_ip_list = sub {
        $ipv4_queries++;
        return { answers => [], listed => 0 };
    };
    my $rbl_result = Postfilter::Checks::Reputation->run_rbl($ipv4_context);
    ok($rbl_result->is_pass, 'IPv4-only DNSBL remains active for an IPv4 client');
}
is($ipv4_queries, 1, 'IPv4 client performs exactly one query against the IPv4-only provider');

my $invalid_family_config = base_config();
$invalid_family_config->{dnsbl} = [{
    id          => 'invalid-family-test',
    zone        => 'dnsbl.invalid',
    ip_versions => ['ipv4', 'bogus'],
}];
my $validator = Postfilter::Config->new(
    source    => '/nonexistent/postfilter.toml',
    state_dir => '/tmp/postfilter-invalid-family-test',
);
my $family_warnings = $validator->validate_and_sanitize($invalid_family_config);
ok(!$invalid_family_config->{dnsbl}[0]{enabled}, 'invalid DNSBL ip_versions disables only that provider');
like(join("\n", @{$family_warnings}), qr/ip_versions contains an unsupported/, 'invalid DNSBL address family produces a configuration warning');

# 5. The installer must discover an innconfval that is only present in PATH.
my $tmp = tempdir(CLEANUP => 1);
my $bin = "$tmp/bin";
make_path($bin);
my $fake = "$bin/innconfval";
open my $fh, '>:raw', $fake or die $!;
print {$fh} <<'SH';
#!/bin/sh
case "$1" in
  pathfilter) echo /home/news/bin/filter ;;
  pathetc) echo /home/news/etc ;;
  pathdb) echo /home/news/db ;;
  pathspool) echo /home/news/spool ;;
  pathbin) echo /home/news/bin ;;
  *) exit 1 ;;
esac
SH
close $fh or die $!;
chmod 0755, $fake or die $!;

local $ENV{PATH} = "$bin:/usr/bin:/bin";
my $command = "$^X installer/install-postfilter --dry-run --skip-dependency-check 2>&1";
my $output = qx{$command};
is($? >> 8, 0, 'installer dry-run succeeds with innconfval found only through PATH') or diag $output;
like($output, qr{config_dir\s+/home/news/etc/postfilter-ng}, 'PATH innconfval supplies pathetc');
like($output, qr{state_dir\s+/home/news/db/postfilter-ng}, 'PATH innconfval supplies pathdb');
like($output, qr{filter_dir\s+/home/news/bin/filter}, 'PATH innconfval supplies pathfilter');

# Existing compatibility aliases remain accepted by the parser/runtime so an
# upgrade does not invalidate an rc7 operator file; only the shipped defaults
# have been simplified.
my $config_source = _slurp('lib/Postfilter/Config.pm');
like($config_source, qr/active_file html_output public_suffix_file/, 'legacy paths.html_output alias remains accepted');
like($config_source, qr/database_privacy header_pseudonym html_report tor_header/, 'legacy keys.database_privacy alias remains accepted');

done_testing;

sub _slurp {
    my ($path) = @_;
    open my $handle, '<:raw', $path or die $!;
    local $/;
    my $text = <$handle>;
    close $handle or die $!;
    return $text;
}
