# Regression tests for the 2026.08.1-rc2 upgrade/configuration improvements.

use strict;
use warnings;

use File::Spec;
use File::Temp qw(tempdir);
use Test::More;
use lib 'lib';
use lib 'tests/lib';

use Postfilter::Checks::Rules;
use Postfilter::Checks::Style;
use Postfilter::Crypto;
use Postfilter::HeaderTransform;
use Postfilter::InstallUpgrade qw(configuration_matches_distribution);
use Postfilter::NG;
use Postfilter::Version;
use TestPostfilter qw(base_config build_context current_rfc_date test_logger);

# 1. X-Postfilter is generated by the runtime and cannot be made stale by an
# older preserved [new_headers] value.  Site-local headers remain configurable.
my $header_config = base_config();
$header_config->{headers}{include_new_headers} = 1;
$header_config->{new_headers}{'X-Postfilter'} = 'Postfilter-NG 1900.01.1-stale';
$header_config->{new_headers}{'X-Notice-1'} =
    'A poorly unconfigured system, abandoned to themself';
my $header_context = build_context(config => $header_config);
my $header_result = Postfilter::HeaderTransform->apply($header_context);
ok($header_result->is_pass, 'normal header finalisation passes');
is(
    $header_context->{headers}{'X-Postfilter'},
    'Postfilter-NG ' . Postfilter::Version::version(),
    'X-Postfilter is generated from the runtime version',
);
is(
    $header_context->{headers}{'X-Notice-1'},
    'A poorly unconfigured system, abandoned to themself',
    'site-local BOFH notice remains configurable',
);
unlike(
    $header_context->{headers}{'X-Postfilter'},
    qr/stale/,
    'preserved stale X-Postfilter configuration cannot override runtime metadata',
);

# 2. A trusted local control injector can skip only the Control restriction
# without receiving a full pipeline bypass.
my $control_config = base_config();
$control_config->{trusted_profile} = [{
    id              => 'local-control-test',
    enabled         => 1,
    priority        => 3000,
    match_mode      => 'all',
    source_networks => ['127.0.0.1/32', '::1/128'],
    header_match    => [{
        name    => 'Control',
        pattern => '^(?:checkgroups|newgroup|rmgroup)\\b',
    }],
    skip_checks => ['style.control'],
    full_bypass => 0,
}];
my $control_headers = {
    From         => 'News Admin <admin@example.invalid>',
    Newsgroups   => 'control,control.checkgroups',
    Subject      => 'checkgroups',
    Date         => current_rfc_date(),
    'Message-ID' => '<checkgroups-rc2@example.invalid>',
    Control      => 'checkgroups',
};
my $plain_control = build_context(
    config     => base_config(),
    headers    => $control_headers,
    attributes => {
        hostname  => 'localhost',
        ipaddress => '::1',
        interface => 'localhost',
    },
);
is(
    Postfilter::Checks::Style->run($plain_control)->legacy,
    1,
    'checkgroups is rejected without an explicit trusted skip',
);
my $trusted_control = build_context(
    config     => $control_config,
    headers    => $control_headers,
    attributes => {
        hostname  => 'localhost',
        ipaddress => '::1',
        interface => 'localhost',
    },
);
my $profile = Postfilter::Checks::Rules->apply_trusted_profile($trusted_control);
is($profile->{id}, 'local-control-test', 'local control trusted profile matches');
ok($trusted_control->skip('style.control'), 'trusted profile enables only style.control skip');
ok(!$profile->{full_bypass}, 'granular control authorization is not a full bypass');
ok(
    Postfilter::Checks::Style->run($trusted_control)->is_pass,
    'checkgroups passes when only style.control is skipped',
);

# 3. Installer auto-update detection is deliberately byte-exact after the same
# path substitutions used for .dist files.  Any local edit forces preservation.
my $upgrade_root = tempdir(CLEANUP => 1);
my $previous_source = File::Spec->catfile($upgrade_root, 'previous.toml');
my $installed = File::Spec->catfile($upgrade_root, 'installed.toml');
open my $previous_fh, '>:raw', $previous_source or die $!;
print {$previous_fh} <<'TOML';
[paths]
state_dir = "/var/lib/news/postfilter-ng"
TOML
close $previous_fh or die $!;
open my $installed_fh, '>:raw', $installed or die $!;
print {$installed_fh} <<'TOML';
[paths]
state_dir = "/home/news/db/postfilter-ng"
TOML
close $installed_fh or die $!;
my $replacements = [[
    '/var/lib/news/postfilter-ng',
    '/home/news/db/postfilter-ng',
]];
ok(
    configuration_matches_distribution(
        installed    => $installed,
        source       => $previous_source,
        replacements => $replacements,
    ),
    'untouched path-adjusted previous config is safe for automatic replacement',
);
open my $modified_fh, '>>:raw', $installed or die $!;
print {$modified_fh} "# local administrator change\n";
close $modified_fh or die $!;
ok(
    !configuration_matches_distribution(
        installed    => $installed,
        source       => $previous_source,
        replacements => $replacements,
    ),
    'any local byte-level change forces preservation and .dist handling',
);

# 4. The final article_result event contains both the stable reason code and its
# human-readable explanation.
{
    package TestPostfilter::RC2Loader;
    sub new { bless { config => $_[1] }, $_[0] }
    sub maybe_reload { return $_[0]{config} }
}
my $log_config = base_config();
$log_config->{logging}{log_accepted} = 1;
$log_config->{logging}{log_rejected} = 1;
my $log_logger = test_logger();
my $engine = bless {
    config   => $log_config,
    crypto   => Postfilter::Crypto->new(logger => $log_logger),
    database => undef,
    loader   => TestPostfilter::RC2Loader->new($log_config),
    logger   => $log_logger,
    suffixes => {},
}, 'Postfilter::NG';
my $response = $engine->process_article(
    attributes => {
        hostname  => 'localhost',
        ipaddress => '127.0.0.1',
        interface => 'localhost',
    },
    headers => {
        From         => 'Example <example@example.invalid>',
        Newsgroups   => 'local.test',
        Subject      => 'control test',
        Date         => current_rfc_date(),
        'Message-ID' => '<reason-text-rc2@example.invalid>',
        Control      => 'checkgroups',
    },
    body => "control fixture\n",
    user => '',
);
my ($article_event) = grep {
    $_->{message} eq 'article_result'
} @{ $log_logger->{events} };
ok($article_event, 'article_result was emitted');
is($article_event->{fields}{reason}, 'PF-HEADER-001', 'stable reason code is retained');
is(
    $article_event->{fields}{reason_text},
    'Control messages are forbidden',
    'human-readable reason is logged beside the stable code',
);
like($response, qr/Control messages are forbidden/, 'NNTP response remains unchanged');

# 5. Shipped config and installer expose the intended operator UX.
my $main = _slurp('conf/postfilter.toml');
unlike($main, qr/^X-Postfilter\s*=/m, 'X-Postfilter is no longer configured in TOML');
like(
    $main,
    qr/^X-Notice-1\s*=\s*"A poorly unconfigured system, abandoned to themself"$/m,
    'default BOFH X-Notice-1 is shipped',
);
my $installer = _slurp('installer/install-postfilter');
like($installer, qr/configuration_matches_distribution/, 'installer detects untouched previous config');
like($installer, qr/Preserving locally modified configuration/, 'installer explicitly reports local preservation');
like($installer, qr/ACTIVE configuration file:/, 'installer identifies active configuration path');
like($installer, qr/Source examples \(not loaded\)/, 'installer distinguishes source examples from runtime config');

sub _slurp {
    my ($path) = @_;
    open my $fh, '<:raw', $path or die $!;
    local $/;
    my $text = <$fh>;
    close $fh or die $!;
    return $text;
}

done_testing;
