package Postfilter::Report;

use strict;
use warnings;

=head1 NAME

Postfilter::Report - Atomic static HTML statistics generation.

=head1 DESCRIPTION

The report is generated by C<postfilterctl report-generate>, normally from cron
or a systemd timer.  The nnrpd hook never writes HTML during a POST.  A failed
report leaves the previously published file untouched because output is written
atomically.

Identity display modes are independent from SQLite storage privacy:

  plain       publish the locally recovered value
  redacted    publish a small prefix and suffix
  hmac        publish a stable non-reversible pseudonym
  encrypted   publish a reversible authenticated token

The default is C<hmac>.  C<encrypted> uses the dedicated HTML-report key and can
be decoded only with C<postfilterctl decrypt-report-value>.

=cut

use POSIX qw(strftime);
use Time::HiRes qw(time);

use Postfilter::Util qw(atomic_write hmac_id slurp);

# Function: generate
# Purpose: Builds and atomically publishes a privacy-aware static HTML report from SQLite.
# Parameters: $class, %arguments
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub generate {
    my ($class, %arguments) = @_;

    my $database = $arguments{database};
    my $config   = $arguments{config};
    my $crypto   = $arguments{crypto};
    my $logger   = $arguments{logger};

    my $dbh = $database->connect
        or die "SQLite database is not available\n";

    my $hours = $config->{html_report}{hours} // 168;
    my $since = time - ($hours * 3_600);

    my (
        $total,
        $accepted,
        $rejected,
        $discarded,
        $audit_would_reject,
        $tor,
        $average_latency,
        $maximum_latency,
    ) = $dbh->selectrow_array(q{
        SELECT
            COUNT(*),
            SUM(nntp_result = 'accepted'),
            SUM(nntp_result = 'rejected'),
            SUM(nntp_result = 'discarded'),
            SUM(audit_mode = 1 AND would_reject = 1),
            SUM(tor = 1),
            AVG(elapsed_ms),
            MAX(elapsed_ms)
        FROM article_events
        WHERE received_at >= ?
    }, undef, $since);

    my $article_types = $dbh->selectall_arrayref(q{
        SELECT
            article_type,
            COUNT(*) AS total,
            SUM(nntp_result = 'accepted') AS accepted,
            SUM(nntp_result = 'rejected') AS rejected,
            SUM(nntp_result = 'discarded') AS discarded,
            SUM(audit_mode = 1 AND would_reject = 1) AS audit
        FROM article_events
        WHERE received_at >= ?
        GROUP BY article_type
        ORDER BY article_type
    }, { Slice => {} }, $since);

    my $reasons = $dbh->selectall_arrayref(q{
        SELECT article_type, reason_code, legacy_code, reason_text, COUNT(*) AS count
        FROM article_events
        WHERE received_at >= ?
          AND technical_verdict = 'reject'
        GROUP BY article_type, reason_code, legacy_code, reason_text
        ORDER BY count DESC
        LIMIT 20
    }, { Slice => {} }, $since);

    my $rules = $dbh->selectall_arrayref(q{
        SELECT rule_hits.rule_id,
               COUNT(*) AS count,
               SUM(rule_hits.score) AS score
        FROM rule_hits
        JOIN article_events ON article_events.id = rule_hits.event_id
        WHERE article_events.received_at >= ?
        GROUP BY rule_hits.rule_id
        ORDER BY count DESC
        LIMIT 20
    }, { Slice => {} }, $since);

    my $hourly = $dbh->selectall_arrayref(q{
        SELECT
            strftime(
                '%Y-%m-%d %H:00',
                received_at,
                'unixepoch',
                'localtime'
            ) AS bucket,
            COUNT(*) AS total,
            SUM(nntp_result = 'accepted') AS accepted,
            SUM(nntp_result = 'rejected') AS rejected,
            SUM(audit_mode = 1 AND would_reject = 1) AS audit
        FROM article_events
        WHERE received_at >= ?
        GROUP BY bucket
        ORDER BY bucket
    }, { Slice => {} }, $since);

    # Group by the stable lookup columns rather than by the displayed storage
    # columns.  Encrypted storage deliberately uses a fresh nonce for every
    # event, so grouping ciphertext would split one identity into many rows.
    my $identities = $dbh->selectall_arrayref(q{
        WITH grouped_identity AS (
            SELECT client_ip_lookup,
                   auth_user_lookup,
                   MAX(id) AS sample_event_id,
                   COUNT(*) AS count,
                   SUM(technical_verdict = 'reject') AS rejected
            FROM article_events
            WHERE received_at >= ?
            GROUP BY client_ip_lookup, auth_user_lookup
            ORDER BY count DESC
            LIMIT 20
        )
        SELECT article_events.client_ip,
               article_events.auth_user,
               article_events.identity_storage_mode,
               grouped_identity.count,
               grouped_identity.rejected
        FROM grouped_identity
        JOIN article_events
          ON article_events.id = grouped_identity.sample_event_id
        ORDER BY grouped_identity.count DESC
    }, { Slice => {} }, $since);

    my $identity_mode =
        $config->{html_report}{privacy}{identity_mode}
        // 'hmac';
    my $privacy_key;

    if ($identity_mode eq 'hmac' || $identity_mode eq 'encrypted') {
        my $key_path =
            $config->{html_report}{privacy}{key_file}
            // $config->{keys}{html_report};
        $privacy_key = $crypto->load_key($key_path);
    }

    for my $row (@{$identities}) {
        # The database and HTML report have independent privacy policies.
        # Recover encrypted database values locally before applying the report
        # policy.  HMAC database values remain non-reversible pseudonyms.
        $row->{client_ip} = $database->reveal_identity(
            'client_ip',
            $row->{client_ip},
            $row->{identity_storage_mode},
        );
        $row->{auth_user} = $database->reveal_identity(
            'auth_user',
            $row->{auth_user},
            $row->{identity_storage_mode},
        );

        $row->{client_ip} = _protect_report_value(
            $row->{client_ip},
            $identity_mode,
            $privacy_key,
            $crypto,
            'html-ip',
        );
        $row->{auth_user} = _protect_report_value(
            $row->{auth_user},
            $identity_mode,
            $privacy_key,
            $crypto,
            'html-user',
        );
    }

    my $title = _escape_html(
        $config->{html_report}{title}
        // 'Postfilter-NG statistics'
    );
    my $generated = strftime('%Y-%m-%d %H:%M:%S %Z', localtime);

    my $stylesheet = _load_stylesheet($config, $logger);
    my $html = _html_header($title, $stylesheet);
    $html .= "<h1>$title</h1>";
    $html .= '<p class="meta">Generated '
        . _escape_html($generated)
        . '; window: last '
        . _escape_html($hours)
        . ' hours; identity mode: '
        . _escape_html($identity_mode)
        . '.</p>';

    $html .= '<div class="cards">';
    $html .= _card('Processed', $total);
    $html .= _card('Accepted', $accepted);
    $html .= _card('Rejected', $rejected);
    $html .= _card('Discarded', $discarded);
    $html .= _card('Audit would-reject', $audit_would_reject);
    $html .= _card('TOR', $tor);
    for my $row (@{$article_types}) {
        my $label = ucfirst($row->{article_type} // 'unknown') . ' articles';
        $html .= _card($label, $row->{total} // 0);
    }
    $html .= _card(
        'Average latency',
        sprintf('%.2f ms', $average_latency // 0),
    );
    $html .= _card(
        'Maximum latency',
        sprintf('%.2f ms', $maximum_latency // 0),
    );
    $html .= '</div>';

    $html .= '<h2>Text and binary activity</h2>';
    $html .= _table(
        ['Article type', 'Total', 'Accepted', 'Rejected', 'Discarded', 'Audit would-reject'],
        [map {
            [
                $_->{article_type},
                $_->{total},
                $_->{accepted} // 0,
                $_->{rejected} // 0,
                $_->{discarded} // 0,
                $_->{audit} // 0,
            ]
        } @{$article_types}],
    );

    $html .= '<h2>Top rejection reasons</h2>';
    $html .= _table(
        ['Article type', 'Reason', 'Historical code', 'Count', 'Description'],
        [map {
            [
                $_->{article_type},
                $_->{reason_code},
                $_->{legacy_code},
                $_->{count},
                $_->{reason_text},
            ]
        } @{$reasons}],
    );

    $html .= '<h2>Top rule hits</h2>';
    $html .= _table(
        ['Rule ID', 'Matches', 'Score total'],
        [map {
            [$_->{rule_id}, $_->{count}, $_->{score} // 0]
        } @{$rules}],
    );

    $html .= '<h2>Top posting identities</h2>';
    $html .= _table(
        ['Client IP', 'Authenticated user', 'Posts', 'Technical rejects'],
        [map {
            [
                $_->{client_ip},
                $_->{auth_user},
                $_->{count},
                $_->{rejected} // 0,
            ]
        } @{$identities}],
    );

    $html .= '<h2>Hourly activity</h2>';
    $html .= _table(
        ['Hour', 'Total', 'Accepted', 'Rejected', 'Audit would-reject'],
        [map {
            [
                $_->{bucket},
                $_->{total},
                $_->{accepted} // 0,
                $_->{rejected} // 0,
                $_->{audit} // 0,
            ]
        } @{$hourly}],
    );

    $html .= '<p class="small">Postfilter-NG static report. '
        . 'Encrypted values are reversible only with postfilterctl and the '
        . 'dedicated HTML-report key.</p>';
    $html .= '</body></html>';

    my $output_file =
        $config->{html_report}{output_file}
        // $config->{paths}{html_output};
    die "No HTML output file was configured\n" unless $output_file;

    atomic_write($output_file, $html, 0644);

    $logger->result(
        'html_report_generated',
        hours => $hours,
        path  => $output_file,
    ) if $logger;

    return $output_file;
}

# Function: _protect_report_value
# Purpose: Transforms a report identity according to plain, redacted, HMAC, or encrypted policy.
# Parameters: $value, $mode, $key, $crypto, $purpose
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _protect_report_value {
    my ($value, $mode, $key, $crypto, $purpose) = @_;
    $value = '' unless defined $value;

    return $value if $mode eq 'plain';
    return '' if $value eq '';

    if ($mode eq 'redacted') {
        return length($value) <= 5
            ? substr($value, 0, 1) . '…'
            : substr($value, 0, 3) . '…' . substr($value, -2);
    }

    return 'h1:' . hmac_id($value, $key, 24)
        if $mode eq 'hmac';

    return $crypto->encrypt_token($value, $key, $purpose)
        if $mode eq 'encrypted';

    return '';
}

# Function: _load_stylesheet
# Purpose: Loads operator CSS for embedding and falls back to a safe built-in stylesheet.
# Parameters: $config, $logger
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _load_stylesheet {
    my ($config, $logger) = @_;

    my $path = $config->{html_report}{stylesheet_file} // '';
    if (length($path) && -r $path) {
        my $css = eval { slurp($path) };
        return $css if defined($css) && !$@;

        $logger->warning(
            'html_report_stylesheet_read_failed',
            error => $@,
            path  => $path,
        ) if $logger;
    }
    elsif (length($path)) {
        $logger->warning(
            'html_report_stylesheet_unavailable',
            path => $path,
        ) if $logger;
    }

    return <<'CSS';
body {
    background: #f7f7f8;
    color: #171717;
    font-family: system-ui, -apple-system, sans-serif;
    margin: 2rem auto;
    max-width: 1200px;
    padding: 0 1rem;
}
.cards {
    display: grid;
    gap: 1rem;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    margin: 1.5rem 0;
}
.card, table {
    background: white;
    border: 1px solid #ddd;
}
.card {
    border-radius: 10px;
    padding: 1rem;
}
table {
    border-collapse: collapse;
    margin: 1rem 0 2rem;
    width: 100%;
}
th, td {
    border: 1px solid #ddd;
    padding: .55rem .7rem;
    text-align: left;
}
th { background: #eee; }
.meta, .small { color: #666; }
.value { font-size: 1.7rem; font-weight: 700; }
CSS
}

# Function: _html_header
# Purpose: Builds the escaped HTML document prologue and embeds the selected stylesheet.
# Parameters: $title, $stylesheet
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _html_header {
    my ($title, $stylesheet) = @_;

    $stylesheet = '' unless defined $stylesheet;
    $stylesheet =~ s{</style}{<\/style}ig;

    return qq{<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>$title</title>
<style>
$stylesheet
</style>
</head>
<body>};
}

# Function: _card
# Purpose: Builds one escaped summary-card fragment.
# Parameters: $label, $value
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _card {
    my ($label, $value) = @_;
    return '<div class="card"><div class="meta">'
        . _escape_html($label)
        . '</div><div class="value">'
        . _escape_html($value // 0)
        . '</div></div>';
}

# Function: _table
# Purpose: Builds one escaped HTML table from headings and rows.
# Parameters: $headings, $rows
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _table {
    my ($headings, $rows) = @_;

    my $html = '<table><thead><tr>';
    $html .= join '', map {
        '<th>' . _escape_html($_) . '</th>'
    } @{$headings};
    $html .= '</tr></thead><tbody>';

    for my $row (@{$rows}) {
        $html .= '<tr>';
        $html .= join '', map {
            '<td><code>'
                . _escape_html(defined($_) ? $_ : '')
                . '</code></td>'
        } @{$row};
        $html .= '</tr>';
    }

    return $html . '</tbody></table>';
}

# Function: _escape_html
# Purpose: Escapes HTML metacharacters in every database/configuration value before publication.
# Parameters: $value
# Operational notes: Failure behaviour is explicit in the function body and follows the caller’s
#                    configured fail-open/fail-closed policy.
sub _escape_html {
    my ($value) = @_;
    $value = '' unless defined $value;

    $value =~ s/&/&amp;/g;
    $value =~ s/</&lt;/g;
    $value =~ s/>/&gt;/g;
    $value =~ s/"/&quot;/g;
    return $value;
}

1;
